--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PresentKim/runtimeid-polyfill
branches:
  - main
projects:
  runtimeid-polyfill:
    model: virion
    type: library
    lint:
      phpstan: false
    libs:
        - src: PresentKim/accessor/accessor
          version: ^1.0.0
...
